@AccountService_HostAddress = http://localhost:5080

GET {{AccountService_HostAddress}}/accounts/me
Authorization: Bearer <token>

###

PUT {{AccountService_HostAddress}}/accounts/me
Authorization: Bearer <token>
Content-Type: application/json

{
  "displayName": "Martim",
  "preferredStoreId": "continente-colombo",
  "shoppingRadiusKm": 7
}
