// <auto-generated />
using System;
using AccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Migrations
{
    [DbContext(typeof(AccountServiceDbContext))]
    [Migration("20260501190000_AddAccountPushTokens")]
    partial class AddAccountPushTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("AccountService.Data.Entities.AccountPushTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.ToTable("account_push_tokens", (string)null);
                });

            modelBuilder.Entity("AccountService.Data.Entities.FavoriteProductEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("account_id");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("product_id");

                    b.HasKey("AccountId", "ProductId");

                    b.ToTable("favorite_products", (string)null);
                });

            modelBuilder.Entity("AccountService.Data.Entities.AccountPushTokenEntity", b =>
                {
                    b.HasOne("AccountService.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountService.Data.Entities.FavoriteProductEntity", b =>
                {
                    b.HasOne("AccountService.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
